#!/usr/bin/env node
/**
 * FEAT-003 — generates the single authoritative version/update-timestamp
 * file consumed by src/components/VersionFooter.tsx.
 *
 * Source of truth:
 * - version: package.json "version" (X.Y.Z, maintained by developers per
 *   the semantic rules in ROADMAP.md — major.feature.bugfix).
 * - updatedAt: the commit timestamp of the most recent git commit that
 *   touched the active application (this src/frontend/ tree), NOT the
 *   build machine's clock and NOT the end user's browser clock. This
 *   matches the ROADMAP.md requirement that the footer reflect the last
 *   duration_calculator_backend edit, not build time or local time.
 *
 * Runs both locally (predev/prestart, so `npm start` always has current
 * data) and in CI (before typecheck/build), so there is one mechanism,
 * not CI-only magic. Falls back gracefully (a clearly-marked placeholder,
 * never a crash) when git metadata isn't available, e.g. inside an
 * extracted tarball with no .git directory.
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "src", "generated");
const OUT_FILE = path.join(OUT_DIR, "versionInfo.ts");

function readVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
  return pkg.version || "0.0.0";
}

function readUpdatedAtIso() {
  try {
    // Scoped to the active app tree only, so unrelated changes elsewhere
    // in the monorepo (e.g. src/backend/ docs) don't bump the
    // displayed timestamp for a UI the user didn't actually see change.
    const iso = execSync('git log -1 --format=%cI -- .', { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
    if (iso) return iso;
  } catch (e) {
    // no .git available (e.g. extracted artifact) — fall through
  }
  return null;
}

const version = readVersion();
const updatedAtIso = readUpdatedAtIso();

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  OUT_FILE,
  `// AUTO-GENERATED by scripts/generate-version.js — do not edit by hand.\n` +
    `// Regenerated on every install/dev/build. Source of truth: package.json\n` +
    `// "version" + the last git commit touching src/frontend/.\n` +
    `export const APP_VERSION = ${JSON.stringify(version)};\n` +
    `export const UPDATED_AT_ISO: string | null = ${JSON.stringify(updatedAtIso)};\n`,
  "utf8"
);

console.log(`[generate-version] APP_VERSION=${version} UPDATED_AT_ISO=${updatedAtIso ?? "(unavailable)"}`);
